version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: 'user'
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-api

volumes:
  postgres-disk:
